# Generated by Django 4.2.1 on 2023-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bands',
            new_name='Band',
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name_plural': 'bands'},
        ),
    ]
