# Generated by Django 4.2.1 on 2023-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
