# Generated by Django 4.2.1 on 2023-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_song_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview',
            field=models.CharField(max_length=5000),
        ),
    ]
