# Generated by Django 4.2.1 on 2023-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_song_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='solo',
            field=models.BooleanField(default=False),
        ),
    ]
